export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FETCH_MEMBERS_REQUEST = 'FETCH_MEMBERS_REQUEST';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_FAILURE = 'FETCH_MEMBERS_FAILURE';

export const ADD_MEMBER_REQUEST = 'ADD_MEMBER_REQUEST';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_FAILURE = 'ADD_MEMBER_FAILURE';

export const FETCH_ACADEMIC_TITLES_REQUEST = 'FETCH_ACADEMIC_TITLES_REQUEST';
export const FETCH_ACADEMIC_TITLES_SUCCESS = 'FETCH_ACADEMIC_TITLES_SUCCESS';
export const FETCH_ACADEMIC_TITLES_FAILURE = 'FETCH_ACADEMIC_TITLES_FAILURE';

export const FETCH_EDUCATION_TITLES_REQUEST = 'FETCH_EDUCATION_TITLES_REQUEST';
export const FETCH_EDUCATION_TITLES_SUCCESS = 'FETCH_EDUCATION_TITLES_SUCCESS';
export const FETCH_EDUCATION_TITLES_FAILURE = 'FETCH_EDUCATION_TITLES_FAILURE';

export const FETCH_SCIENTIFIC_FIELDS_REQUEST = 'FETCH_SCIENTIFIC_FIELDS_REQUEST';
export const FETCH_SCIENTIFIC_FIELDS_SUCCESS = 'FETCH_SCIENTIFIC_FIELDS_SUCCESS';
export const FETCH_SCIENTIFIC_FIELDS_FAILURE = 'FETCH_SCIENTIFIC_FIELDS_FAILURE';

