export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const FETCH_MEMBERS_REQUEST = "FETCH_MEMBERS_REQUEST";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAILURE = "FETCH_MEMBERS_FAILURE";

export const ADD_MEMBER_REQUEST = "ADD_MEMBER_REQUEST";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_FAILURE = "ADD_MEMBER_FAILURE";

export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_FAILURE = "DELETE_MEMBER_FAILURE";

export const UPDATE_MEMBER_REQUEST = "UPDATE_MEMBER_REQUEST";
export const UPDATE_MEMBER_SUCCESS = "UPDATE_MEMBER_SUCCESS";
export const UPDATE_MEMBER_FAILURE = "UPDATE_MEMBER_FAILURE";

export const GET_MEMBER_REQUEST = "GET_MEMBER_REQUEST";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
export const GET_MEMBER_FAILURE = "GET_MEMBER_FAILURE";

export const FETCH_ACADEMIC_TITLES_REQUEST = "FETCH_ACADEMIC_TITLES_REQUEST";
export const FETCH_ACADEMIC_TITLES_SUCCESS = "FETCH_ACADEMIC_TITLES_SUCCESS";
export const FETCH_ACADEMIC_TITLES_FAILURE = "FETCH_ACADEMIC_TITLES_FAILURE";

export const FETCH_EDUCATION_TITLES_REQUEST = "FETCH_EDUCATION_TITLES_REQUEST";
export const FETCH_EDUCATION_TITLES_SUCCESS = "FETCH_EDUCATION_TITLES_SUCCESS";
export const FETCH_EDUCATION_TITLES_FAILURE = "FETCH_EDUCATION_TITLES_FAILURE";

export const FETCH_SCIENTIFIC_FIELDS_REQUEST =
  "FETCH_SCIENTIFIC_FIELDS_REQUEST";
export const FETCH_SCIENTIFIC_FIELDS_SUCCESS =
  "FETCH_SCIENTIFIC_FIELDS_SUCCESS";
export const FETCH_SCIENTIFIC_FIELDS_FAILURE =
  "FETCH_SCIENTIFIC_FIELDS_FAILURE";

export const FETCH_DEPARTMENTS_REQUEST = "FETCH_DEPARTMENTS_REQUEST";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_FAILURE = "FETCH_DEPARTMENTS_FAILURE";

export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_FAILURE = "GET_DEPARTMENT_FAILURE";

export const ADD_DEPARTMENT_REQUEST = "ADD_DEPARTMENT_REQUEST";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILURE = "DELETE_DEPARTMENT_FAILURE";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILURE = "UPDATE_DEPARTMENT_FAILURE";

export const FETCH_SUBJECTS_REQUEST = "FETCH_SUBJECTS_REQUEST";
export const FETCH_SUBJECTS_SUCCESS = "FETCH_SUBJECTS_SUCCESS";
export const FETCH_SUBJECTS_FAILURE = "FETCH_SUBJECTS_FAILURE";

export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST";
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS";
export const GET_SUBJECT_FAILURE = "GET_SUBJECT_FAILURE";

export const ADD_SUBJECT_REQUEST = "ADD_SUBJECT_REQUEST";
export const ADD_SUBJECT_SUCCESS = "ADD_SUBJECT_SUCCESS";
export const ADD_SUBJECT_FAILURE = "ADD_SUBJECT_FAILURE";

export const DELETE_SUBJECT_REQUEST = "DELETE_SUBJECT_REQUEST";
export const DELETE_SUBJECT_SUCCESS = "DELETE_SUBJECT_SUCCESS";
export const DELETE_SUBJECT_FAILURE = "DELETE_SUBJECT_FAILURE";

export const UPDATE_SUBJECT_REQUEST = "UPDATE_SUBJECT_REQUEST";
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS";
export const UPDATE_SUBJECT_FAILURE = "UPDATE_SUBJECT_FAILURE";

export const FETCH_SUBJECTS_BY_DEPARTMENT_REQUEST =
  "FETCH_SUBJECTS_BY_DEPARTMENT_REQUEST";
export const FETCH_SUBJECTS_BY_DEPARTMENT_SUCCESS =
  "FETCH_SUBJECTS_BY_DEPARTMENT_SUCCESS";
export const FETCH_SUBJECTS_BY_DEPARTMENT_FAILURE =
  "FETCH_SUBJECTS_BY_DEPARTMENT_FAILURE";

export const CLEAR_ADD_SUBJECT_STATE = "CLEAR_ADD_SUBJECT_STATE";
export const CLEAR_DELETE_SUBJECT_STATE = "CLEAR_DELETE_SUBJECT_STATE";
